### ISSUE TITLE
elasticsearch-5.0.1: Exception "Fielddata is disabled on text fields by default..."

### ISSUE THREAD

**Issue by mguesdon** [nbs-system/naxsi#329]
I'm following https://github.com/nbs-system/naxsi/tree/master/nxapi tutorial.
It's OK until "./nxtool.py -c nxapi.json -x" which fail:
`
# ./nxtool.py -c nxapi.json  -x
# size :1000
# Whitelist(ing) ratio :
Traceback (most recent call last):
  File "./nxtool.py", line 274, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/usr/local/src/naxsi-0.55.1/nxapi/nxapi/nxtransform.py", line 550, in fetch_top
    res = self.search(esq)
  File "/usr/local/src/naxsi-0.55.1/nxapi/nxapi/nxtransform.py", line 619, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 71, in _wrapped
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 569, in search
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 124, in perform_request
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 122, in _raise_error
elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [whitelisted] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.')
`
I've tried to modify nxparse.py to add "fielddata" : "true" in set_mappings() but no luck :-(

Elastic search version: 5.0.1
Naxsi version: 0.55.1

**Comment by s8sg** [comment]
You need to enable field data on all the text fields for searching, which are: 
whitelisted, server, uri, zone, ip

You could update each of them by: 
PUT /nxapi/_mapping/<text_field_name>?update_all_types

**Comment by s8sg** [comment]
Added pull request for the fix: [Fix of 329](https://github.com/nbs-system/naxsi/pull/330)

**Comment by mguesdon** [comment]
Thank you !

I've applied your patch and done:
curl -XDELETE 'http://localhost:9200/nxapi'
./nxtool.py -c nxapi.json --files=...
but same error.
./nxtool.py say "Unable to create the index/collection : nxapi events" So if I well read the code, it doesn't call self.es.indices.put_mapping()

Next I've done: 
PUT /nxapi/_mapping/<text_field_name>?update_all_types 
for each types and it's now OK.


I've retried the whole process using nxapi-documentation as the name index but same problem: "Unable to create the index/collection : nxapi-documentation events" and no "fielddata" property on fileds.

**Comment by s8sg** [comment]
I have updated the PR and doing specific handling for ES 5.X at I couldn't found a common way that could seamlessly for both: 
You need to set:
`ES5_ENABLE=True` in the env

The TTL is not being set. ES 5.X requires ttl to be set on index level, which needs farther discussion. 

Please check/review the patch : [Update of Fix of 329](https://github.com/nbs-system/naxsi/pull/330/commits/017b415d6d49137c6f343d9e500b363dcfee73c2)

**Comment by buixor** [comment]
Thanks @s8sg !

**Comment by buixor** [comment]
Hello,

Can you try from master ? thank @s8sg

**Comment by fernandomariano** [comment]
Hi @buixor @s8sg . 

Looks like this merge is not in the master branch anymore (nxparse.py - there is no "fielddata: true" in any elasticsearch field to fix this issue). 

I'm still getting this error when fielddata is disabled in the ES 5.

```
/opt/nxapi/nxtool.py -c /opt/nxapi/nxapi.json -f 
elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')
```

Thanks,
Fernando
